### ISSUE TITLE
manufacturability warnings for cover.stl at hubs.com

### ISSUE THREAD

**Issue by aaronferrucci** [BlockchainCommons/lethekit#62]
I uploaded the 3 STL files to a 3D printing service, hubs.com. For the cover, I get a manufacturability warning: "mesh integrity: 127 intersecting faces". I tried two different processes, MJF and SLS, both using nylon, and the same warning occurs. 

There's a second warning that seems less severe, "thin walls"; the report says this would be reviewed manually.

Does anyone know if these warnings can be ignored? Alternatively, has anyone successfully printed the case at a printing service? (If so, please provide the URL.)

**Comment by gorazdko** [comment]
> Alternatively, has anyone successfully printed the case at a printing service? (If so, please provide the URL.)

Yes I have, at my local printing service

I don't know about the particular problem you are mentioning but googling suggests it's (often) a false positive on hubs.com, e.g.

https://forums.autodesk.com/t5/fusion-360-support/every-single-stl-file-i-export-has-quot-intersecting-faces-quot/m-p/8943660#M62371

I'd ignore the warnings if it lets you.

@ksedgwic do you have any thoughts?

**Comment by ksedgwic** [comment]
Nothing obvious comes to mind.

**Comment by aaronferrucci** [comment]
Someone from hubs.com got in touch with me. They reviewed the design, and said that it should print fine (the "intersecting faces" warnings can be ignored). I'm trying to print it. I will post my notes here as things happen.

**Comment by aaronferrucci** [comment]
Case from hubs.com arrived, looks good. Seems that the warning from hubs.com's automatic checks is spurious (and they're aware of the issue). Closing this case.

**Comment by ChristopherA** [comment]
@aaronferrucci If you have any notes you’d like to share as PR with advice on using our designs with various third-party serviced, it would be greatly appreciated.
